### ISSUE TITLE
npm run dev 有问题不知道具体原因

### ISSUE THREAD

**Issue by leeyboy1992** [Awheat/vue2-douban-market#9]
![qq 20181030170334](https://user-images.githubusercontent.com/44251677/47707087-de0cf980-dc65-11e8-83f4-3d252d6c029b.png)

**Comment by Awheat** [comment]
@Lymyall 好像跟你的node和npm版本有关系, 把所有的包删掉重新装一下， 不行的话看看node版本升级一下。
